### PR TITLE
Update utils.py

### PR DESCRIPTION
**Pull request by yc-pro-123**
Removing III - II Exam code from III - I arr

### CODE REVIEW

**Review by hemanth-kotagiri — APPROVED** [review]
LGTM.
Thanks @yc-pro-123

**Comment by yc-pro-123** [comment]
Bruh , should you want to clear the cache to set working  ?
Even after placing the exam codes in their correct respective arrays , the problem doesn't seem to be cleared ? 
Once check it ....
[https://results-restapi.up.railway.app/all-r18/20VE1A0506](url)
@hemanth-kotagiri

**Comment by hemanth-kotagiri** [comment]
> Bruh , should you want to clear the cache to set working right ?
> 
> Even after placing the codes in their correct respective arrays , the problem doesn't seem to be cleared ? 
> 
> Once check it ....
> 
> [https://results-restapi.up.railway.app/all-r18/20VE1A0506](endpoint)
> 
> @hemanth-kotagiri 

I haven't yet triggered the deployment. Will do after sometime.

**Comment by yc-pro-123** [comment]
> Bruh , should you want to clear the cache to set working right ? Even after placing the codes in their correct respective arrays , the problem doesn't seem to be cleared ? Once check it .... [https://results-restapi.up.railway.app/all-r18/20VE1A0506](endpoint) @hemanth-kotagiri



> > Bruh , should you want to clear the cache to set working right ?
> > Even after placing the codes in their correct respective arrays , the problem doesn't seem to be cleared ?
> > Once check it ....
> > [https://results-restapi.up.railway.app/all-r18/20VE1A0506](endpoint)
> > @hemanth-kotagiri
> 
> I haven't yet triggered the deployment. Will do after sometime.

Okk Bruh ! 
Thanks !!
Sorry if I disturbed u .. !!! 💥😅

**Pull request merged**
